#!/bin/bash
#
# AI Platform Installer Tool
# One-command installer for the complete AI-driven automation platform
#

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Configuration
INSTALL_DIR="${INSTALL_DIR:-/opt/ai-platform}"
GITHUB_REPO="https://github.com/AIMLDATAPROJECT/Cyberops"
VERSION="1.0.0"

# Logging functions
log_info() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

log_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

log_warn() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Check if running as root
check_root() {
    if [[ $EUID -eq 0 ]]; then
        log_warn "Running as root. Some services may have permission issues."
        read -p "Continue anyway? (y/N): " -n 1 -r
        echo
        if [[ ! $REPLY =~ ^[Yy]$ ]]; then
            exit 1
        fi
    fi
}

# Check system requirements
check_requirements() {
    log_info "Checking system requirements..."
    
    # Check OS
    if [[ "$OSTYPE" == "linux-gnu"* ]]; then
        OS="linux"
    elif [[ "$OSTYPE" == "darwin"* ]]; then
        OS="macos"
    else
        log_error "Unsupported operating system: $OSTYPE"
        exit 1
    fi
    
    # Check architecture
    ARCH=$(uname -m)
    if [[ "$ARCH" != "x86_64" && "$ARCH" != "arm64" ]]; then
        log_warn "Architecture $ARCH may not be fully supported"
    fi
    
    # Check RAM
    if [[ "$OS" == "linux" ]]; then
        RAM_MB=$(free -m | awk '/^Mem:/{print $2}')
    else
        RAM_MB=$(sysctl -n hw.memsize | awk '{print int($1/1024/1024)}')
    fi
    
    if [[ $RAM_MB -lt 4096 ]]; then
        log_error "Minimum 4GB RAM required. Found: ${RAM_MB}MB"
        exit 1
    elif [[ $RAM_MB -lt 8192 ]]; then
        log_warn "8GB+ RAM recommended for production. Found: ${RAM_MB}MB"
    fi
    
    # Check disk space
    DISK_GB=$(df -h . | awk 'NR==2 {print $4}' | sed 's/G//')
    if [[ ${DISK_GB%.*} -lt 10 ]]; then
        log_error "Minimum 10GB free disk space required"
        exit 1
    fi
    
    log_success "System requirements met"
}

# Install Docker if not present
install_docker() {
    if command -v docker &> /dev/null; then
        log_info "Docker already installed: $(docker --version)"
        return 0
    fi
    
    log_info "Installing Docker..."
    
    if [[ "$OS" == "linux" ]]; then
        # Install Docker on Linux
        curl -fsSL https://get.docker.com -o get-docker.sh
        sudo sh get-docker.sh
        sudo usermod -aG docker $USER
        rm get-docker.sh
    else
        # macOS - install Docker Desktop
        log_error "Please install Docker Desktop manually from https://www.docker.com/products/docker-desktop"
        exit 1
    fi
    
    log_success "Docker installed successfully"
}

# Install Docker Compose
install_docker_compose() {
    if command -v docker-compose &> /dev/null || docker compose version &> /dev/null; then
        log_info "Docker Compose already installed"
        return 0
    fi
    
    log_info "Installing Docker Compose..."
    
    sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" \
        -o /usr/local/bin/docker-compose
    sudo chmod +x /usr/local/bin/docker-compose
    
    log_success "Docker Compose installed"
}

# Download AI Platform
download_platform() {
    log_info "Downloading AI Platform..."
    
    if [[ -d "$INSTALL_DIR" ]]; then
        log_warn "Installation directory exists: $INSTALL_DIR"
        read -p "Remove and reinstall? (y/N): " -n 1 -r
        echo
        if [[ $REPLY =~ ^[Yy]$ ]]; then
            sudo rm -rf "$INSTALL_DIR"
        else
            log_info "Using existing installation"
            return 0
        fi
    fi
    
    sudo mkdir -p "$INSTALL_DIR"
    
    # Clone from GitHub
    if command -v git &> /dev/null; then
        sudo git clone "$GITHUB_REPO.git" "$INSTALL_DIR"
    else
        # Download as tarball
        curl -L "${GITHUB_REPO}/archive/refs/heads/main.tar.gz" | sudo tar -xz -C "$INSTALL_DIR" --strip-components=1
    fi
    
    sudo chown -R $USER:$USER "$INSTALL_DIR"
    
    log_success "AI Platform downloaded to $INSTALL_DIR"
}

# Interactive configuration wizard
run_wizard() {
    log_info "Starting configuration wizard..."
    
    cd "$INSTALL_DIR"
    
    # Create .env file
    cat > .env << EOF
# AI Platform Configuration
# Generated by installer wizard on $(date)

# Database
POSTGRES_USER=postgres
POSTGRES_PASSWORD=$(openssl rand -base64 32)
POSTGRES_DB=aipm

# Redis
REDIS_PASSWORD=$(openssl rand -base64 16)

# MinIO
MINIO_ACCESS_KEY=minioadmin
MINIO_SECRET_KEY=$(openssl rand -base64 32)

# Vault
VAULT_DEV_ROOT_TOKEN_ID=$(openssl rand -base64 24)

# JWT
JWT_SECRET=$(openssl rand -base64 48)

# Network
NETWORK_SUBNET=192.168.1.0/24
SYSTEM_COUNT=20

# AI Configuration
OLLAMA_HOST=http://ollama:11434
OPENAI_API_KEY=
ANTHROPIC_API_KEY=

# Automation Settings
AUTO_HEAL=true
AUTO_SCALE=true
AUTO_REMEDIATE=true
AUTO_DEPLOY=true
AUTO_ROLLBACK=true

# Monitoring
GRAFANA_ADMIN_USER=admin
GRAFANA_ADMIN_PASSWORD=$(openssl rand -base64 16)

# Slack Notifications (optional)
SLACK_WEBHOOK_URL=
SLACK_CHANNEL=#ai-platform-alerts
EOF
    
    echo
    echo "========================================="
    echo "   AI Platform Configuration Wizard"
    echo "========================================="
    echo
    
    # Ask for custom settings
    read -p "Enter network subnet [192.168.1.0/24]: " subnet
    subnet=${subnet:-192.168.1.0/24}
    sed -i "s/NETWORK_SUBNET=.*/NETWORK_SUBNET=$subnet/" .env
    
    read -p "Enter system count [20]: " count
    count=${count:-20}
    sed -i "s/SYSTEM_COUNT=.*/SYSTEM_COUNT=$count/" .env
    
    read -p "Enter Slack webhook URL (optional): " slack_url
    if [[ ! -z "$slack_url" ]]; then
        sed -i "s|SLACK_WEBHOOK_URL=|SLACK_WEBHOOK_URL=$slack_url|" .env
    fi
    
    read -p "Enter Slack channel [#ai-platform-alerts]: " slack_channel
    slack_channel=${slack_channel:-#ai-platform-alerts}
    sed -i "s/SLACK_CHANNEL=.*/SLACK_CHANNEL=$slack_channel/" .env
    
    # Optional: External AI providers
    echo
    echo "External AI Providers (optional - leave blank to use local Ollama):"
    read -p "OpenAI API Key: " openai_key
    if [[ ! -z "$openai_key" ]]; then
        sed -i "s/OPENAI_API_KEY=/OPENAI_API_KEY=$openai_key/" .env
    fi
    
    echo
    log_success "Configuration saved to .env"
}

# Create CLI tool
create_cli_tool() {
    log_info "Creating CLI management tool..."
    
    sudo tee /usr/local/bin/aipm > /dev/null << 'EOF'
#!/bin/bash
# AI Platform Management CLI

INSTALL_DIR="${INSTALL_DIR:-/opt/ai-platform}"

case "$1" in
    start)
        echo "Starting AI Platform..."
        cd "$INSTALL_DIR" && docker compose up -d
        echo "✅ AI Platform started!"
        echo "Dashboard: http://localhost:8080"
        echo "n8n: http://localhost:5678"
        ;;
    stop)
        echo "Stopping AI Platform..."
        cd "$INSTALL_DIR" && docker compose down
        echo "✅ AI Platform stopped"
        ;;
    restart)
        echo "Restarting AI Platform..."
        cd "$INSTALL_DIR" && docker compose restart
        echo "✅ AI Platform restarted"
        ;;
    status)
        cd "$INSTALL_DIR" && docker compose ps
        ;;
    logs)
        service="${2:-}"
        if [[ -z "$service" ]]; then
            cd "$INSTALL_DIR" && docker compose logs -f
        else
            cd "$INSTALL_DIR" && docker compose logs -f "$service"
        fi
        ;;
    update)
        echo "Updating AI Platform..."
        cd "$INSTALL_DIR" && docker compose pull && docker compose up -d
        echo "✅ AI Platform updated"
        ;;
    backup)
        backup_dir="/backup/aipm-$(date +%Y%m%d-%H%M%S)"
        mkdir -p "$backup_dir"
        cd "$INSTALL_DIR"
        docker exec aipm-postgres pg_dump -U postgres aipm > "$backup_dir/database.sql" 2>/dev/null || echo "⚠️ Database backup skipped"
        cp -r n8n_data "$backup_dir/" 2>/dev/null || true
        cp -r shared "$backup_dir/" 2>/dev/null || true
        cp .env "$backup_dir/" 2>/dev/null || true
        echo "✅ Backup created: $backup_dir"
        ;;
    reset)
        read -p "⚠️ This will delete all data! Are you sure? (yes/no): " confirm
        if [[ "$confirm" == "yes" ]]; then
            cd "$INSTALL_DIR" && docker compose down -v
            echo "✅ AI Platform reset"
        else
            echo "Cancelled"
        fi
        ;;
    wizard)
        cd "$INSTALL_DIR" && ./install.sh --wizard
        ;;
    help|*)
        echo "AI Platform Management CLI"
        echo ""
        echo "Usage: aipm <command> [options]"
        echo ""
        echo "Commands:"
        echo "  start       Start all services"
        echo "  stop        Stop all services"
        echo "  restart     Restart all services"
        echo "  status      Show service status"
        echo "  logs [svc]  View logs (optionally for specific service)"
        echo "  update      Update to latest version"
        echo "  backup      Create backup of all data"
        echo "  reset       ⚠️ Reset all data (dangerous!)"
        echo "  wizard      Run configuration wizard"
        echo "  help        Show this help"
        echo ""
        echo "Examples:"
        echo "  aipm start           # Start the platform"
        echo "  aipm logs orchestrator  # View orchestrator logs"
        ;;
esac
EOF

    sudo chmod +x /usr/local/bin/aipm
    log_success "CLI tool installed: run 'aipm' to manage the platform"
}

# Start services
start_services() {
    log_info "Starting AI Platform services..."
    
    cd "$INSTALL_DIR"
    
    # Pull latest images
    docker compose pull
    
    # Start infrastructure first
    log_info "Starting infrastructure..."
    docker compose up -d postgres redis minio vault
    
    log_info "Waiting for infrastructure to initialize..."
    sleep 30
    
    # Start monitoring
    log_info "Starting monitoring..."
    docker compose up -d prometheus grafana
    
    # Start core services
    log_info "Starting core services..."
    docker compose up -d orchestrator ollama
    
    # Start agents
    log_info "Starting agents..."
    docker compose up -d ai-agent data-agent devops-agent netmon-agent security-agent plaintext-api
    
    # Start n8n
    log_info "Starting n8n..."
    docker compose up -d n8n
    
    # Start nginx
    log_info "Starting web server..."
    docker compose up -d nginx
    
    log_success "All services started!"
}

# Verify installation
verify_installation() {
    log_info "Verifying installation..."
    
    cd "$INSTALL_DIR"
    
    # Check services
    services=("orchestrator" "ai-agent" "data-agent" "devops-agent" "netmon-agent" "security-agent")
    
    for service in "${services[@]}"; do
        if docker compose ps | grep -q "$service"; then
            log_success "✓ $service running"
        else
            log_warn "✗ $service not running"
        fi
    done
    
    # Test API
    if curl -s http://localhost:8000/health > /dev/null 2>&1; then
        log_success "✓ Orchestrator API responding"
    else
        log_warn "✗ Orchestrator API not responding yet (may need more time)"
    fi
    
    echo
    log_success "Installation verification complete!"
}

# Print final instructions
print_instructions() {
    echo
    echo "========================================="
    echo "   🎉 AI Platform Installation Complete!"
    echo "========================================="
    echo
    echo "Access your AI Platform:"
    echo "  📊 Dashboard:    http://localhost:8080"
    echo "  🤖 n8n:          http://localhost:5678"
    echo "  📈 Grafana:      http://localhost:3000"
    echo "  📚 API Docs:     http://localhost:8000/docs"
    echo
    echo "Management Commands:"
    echo "  aipm start      - Start the platform"
    echo "  aipm stop       - Stop the platform"
    echo "  aipm status     - Check service status"
    echo "  aipm logs       - View logs"
    echo "  aipm backup     - Create backup"
    echo
    echo "Installation Directory: $INSTALL_DIR"
    echo
    echo "Next Steps:"
    echo "  1. Open http://localhost:8080 to access the dashboard"
    echo "  2. Configure n8n workflows at http://localhost:5678"
    echo "  3. Import workflows from $INSTALL_DIR/workflows/n8n/"
    echo "  4. Activate workflows for automation"
    echo
    echo "Documentation:"
    echo "  - Implementation: $INSTALL_DIR/IMPLEMENTATION.md"
    echo "  - Deployment: $INSTALL_DIR/DEPLOYMENT.md"
    echo
    echo "========================================="
}

# Main installation flow
main() {
    echo "========================================="
    echo "   AI Platform Installer v$VERSION"
    echo "========================================="
    echo
    
    # Check for flags
    if [[ "$1" == "--wizard" ]]; then
        run_wizard
        exit 0
    fi
    
    if [[ "$1" == "--help" || "$1" == "-h" ]]; then
        echo "Usage: ./install.sh [options]"
        echo
        echo "Options:"
        echo "  --wizard    Run configuration wizard only"
        echo "  --help      Show this help"
        echo
        echo "Environment Variables:"
        echo "  INSTALL_DIR    Installation directory (default: /opt/ai-platform)"
        exit 0
    fi
    
    # Run installation steps
    check_root
    check_requirements
    install_docker
    install_docker_compose
    download_platform
    run_wizard
    create_cli_tool
    start_services
    verify_installation
    print_instructions
}

# Run main function
main "$@"
